In [2]:
!python3.14 -m pip install pandas wordfreq

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rayala.adityar/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rayala.adityar/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 21.6 MB/s  0:00:00 eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.1

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

In [1]:
import pandas as pd

In [73]:
# 
# df = pd.read_json('/Users/rayala.adityar/Workspace/Repos/Modiji Audio/genvoice.ConversationInfo.json')
# 11_Mar_2025
df = pd.read_json('/Users/rayala.adityar/Downloads/carrier_mail 2/pm_speech_11Mar.json')

In [24]:
df['speaker_id'].isin(['Guest-2','Guest-4'])

0      False
1      False
2      False
3      False
4      False
       ...
183     True
184     True
185     True
186     True
187     True
Name: speaker_id, Length: 188, dtype: bool

In [74]:
# session_ids = ["7562daca-f988-41f4-bb63-8edce96e41b0","0de2b2da-5389-472f-8007-4e25d6525fc5"]
# df2 = df[df['session_id'].isin(session_ids)]
# df2['created_at'] = (
#     pd.to_datetime(df2['created_at'].apply(lambda x: x['$date']), utc=True)
#     .dt.tz_convert('Asia/Kolkata')
# )
# latency_offset_by_session = {
#     "0de2b2da-5389-472f-8007-4e25d6525fc5": 1.5,
#     "7562daca-f988-41f4-bb63-8edce96e41b0": 0.7,
# }
# df2['total_latency'] = (
#     df2['llm_latency_seconds']
#     + df2['tts_generation_delay_seconds']
#     + df2['session_id'].map(latency_offset_by_session).fillna(0.0)
# )
# 11_mar_2025
session_ids = ["04ce446d-5396-45c9-91e5-57906365fa10"]
guests = ['Guest-4']
df2 = df[df['session_id'].isin(session_ids) & df['speaker_id'].isin(guests)]
df2['created_at'] = (
    pd.to_datetime(df2['created_at'].apply(lambda x: x['$date']), utc=True)
    .dt.tz_convert('Asia/Kolkata')
)
latency_offset_by_session = {
    "04ce446d-5396-45c9-91e5-57906365fa10": 1.5,
}
df2['total_latency'] = (
    df2['llm_latency_seconds']
    + df2['tts_generation_delay_seconds']
    + df2['session_id'].map(latency_offset_by_session).fillna(0.0)
)

In [75]:
df2.sort_values(by='created_at', ascending=True)

,_id,doc_type,session_id,timestamp,source_text,source_text_length,translated_texts,audio_base64,audio_base64s,llm_latency_seconds,tts_generation_delay_seconds,tts_first_token_latency_seconds,speaker_id,created_at,updated_at,total_latency
26,{'$oid': '69b12e246b023d0cb6dd3731'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:03.969Z'},"नमस्कार, हम एरनाकुलम।",21,"{'malayalam': 'നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നി...",UklGRsSFBABXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsSFBABXQVZFZm10IBAAAAABAAE...,0.360,0.830,0.140,Guest-4,2026-03-11 14:26:04.801000+05:30,{'$date': '2026-03-11T08:56:04.801Z'},2.690
27,{'$oid': '69b12e316b023d0cb6dd3732'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:16.565Z'},जय केरला।,9,{'malayalam': 'ജയ് കേരളം.'},UklGRhR6AgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRhR6AgBXQVZFZm10IBAAAAABAAE...,0.255,0.510,0.143,Guest-4,2026-03-11 14:26:17.076000+05:30,{'$date': '2026-03-11T08:56:17.076Z'},2.265
28,{'$oid': '69b12e3e6b023d0cb6dd3733'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:29.440Z'},10 डेज़ और तगड़े।,17,"{'malayalam': '10 ദിവസത്തേക്ക് ഇത് മതിയാകും, ക...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,0.330,0.694,0.145,Guest-4,2026-03-11 14:26:30.136000+05:30,{'$date': '2026-03-11T08:56:30.136Z'},2.524
29,{'$oid': '69b12e456b023d0cb6dd3734'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:36.708Z'},केरला को।,9,{'malayalam': 'കേരളത്തിലേക്ക്.'},UklGRlQvAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRlQvAQBXQVZFZm10IBAAAAABAAE...,0.193,0.306,0.141,Guest-4,2026-03-11 14:26:37.015000+05:30,{'$date': '2026-03-11T08:56:37.015Z'},1.999
30,{'$oid': '69b12e4d6b023d0cb6dd3735'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:45.073Z'},"केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...",50,"{'malayalam': 'കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്,...",UklGRrSNAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRrSNAwBXQVZFZm10IBAAAAABAAE...,0.360,0.692,0.152,Guest-4,2026-03-11 14:26:45.767000+05:30,{'$date': '2026-03-11T08:56:45.767Z'},2.552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,{'$oid': '69b136786b023d0cb6dd37cd'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.563Z'},ये दिखा रहा है।,15,{'malayalam': 'അത് കാണിക്കുകയാണ്.'},UklGRsQTAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsQTAQBXQVZFZm10IBAAAAABAAE...,0.242,0.288,0.142,Guest-4,2026-03-11 15:01:36.852000+05:30,{'$date': '2026-03-11T09:31:36.852Z'},2.030
183,{'$oid': '69b1367b6b023d0cb6dd37ce'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:38.339Z'},यहाँ आने वाले चुनावों में हवा का रुख क्या होगा...,91,{'malayalam': 'വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളി...,UklGRkRiBQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkRiBQBXQVZFZm10IBAAAAABAAE...,0.551,1.040,0.145,Guest-4,2026-03-11 15:01:39.380000+05:30,{'$date': '2026-03-11T09:31:39.380Z'},3.091
184,{'$oid': '69b1367b6b023d0cb6dd37cf'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.910Z'},केरल में बनने वाली बीजेपी एनडीए सरकार यहाँ के ...,155,{'malayalam': 'കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള...,UklGRtTTDwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRtTTDwBXQVZFZm10IBAAAAABAAE...,1.092,2.916,0.141,Guest-4,2026-03-11 15:01:39.830000+05:30,{'$date': '2026-03-11T09:31:39.830Z'},5.508
186,{'$oid': '69b136a26b023d0cb6dd37d1'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:17.570Z'},मेरे साथ बोलिए भारत माता की।,28,"{'malayalam': 'എന്നൊപ്പം ചേർന്ന് ""ഭാരത് മാതാ ...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,0.425,0.707,0.150,Guest-4,2026-03-11 15:02:18.279000+05:30,{'$date': '2026-03-11T09:32:18.279Z'},2.632
187,{'$oid': '69b136ac6b023d0cb6dd37d2'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:27.622Z'},भारत माता के भारत माता के वंदे वंदे।,36,"{'malayalam': 'ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന...",UklGRjSxAgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRjSxAgBXQVZFZm10IBAAAAABAAE...,0.379,0.554,0.151,Guest-4,2026-03-11 15:02:28.178000+05:30,{'$date': '2026-03-11T09:32:28.178Z'},2.433

In [76]:
import re
from wordfreq import zipf_frequency

ENGLISH_THRESHOLD = 0.90

def english_word_metrics(text: str) -> tuple[int, int, float]:
    tokens = re.findall(r"[A-Za-z']+", str(text).lower())
    total_words = len(tokens)
    if total_words == 0:
        return 0, 0, 0.0

    english_words = sum(1 for token in tokens if zipf_frequency(token, "en") > 0)
    ratio = english_words / total_words
    return english_words, total_words, ratio

metrics = df2['source_text'].fillna('').apply(english_word_metrics)

df2[['english_words_detected', 'total_words', 'english_word_ratio']] = pd.DataFrame(
    metrics.tolist(),
    index=df2.index,
)

df2['is_english_by_vocab'] = df2['english_word_ratio'] > ENGLISH_THRESHOLD
df2['asr_decision'] = df2['is_english_by_vocab'].map({
    True: 'accept',
    False: 'reject',
})

sort_col = 'created_at' if 'created_at' in df2.columns else 'timestamp'
sorted_df2 = df2.sort_values(by=sort_col, ascending=False)

sorted_df2[[
    'session_id',
    'source_text',
    'english_words_detected',
    'total_words',
    'english_word_ratio',
    'asr_decision',
]].head(20)

,session_id,source_text,english_words_detected,total_words,english_word_ratio,asr_decision
187,04ce446d-5396-45c9-91e5-57906365fa10,भारत माता के भारत माता के वंदे वंदे।,0,0,0.0,reject
186,04ce446d-5396-45c9-91e5-57906365fa10,मेरे साथ बोलिए भारत माता की।,0,0,0.0,reject
184,04ce446d-5396-45c9-91e5-57906365fa10,केरल में बनने वाली बीजेपी एनडीए सरकार यहाँ के ...,0,0,0.0,reject
183,04ce446d-5396-45c9-91e5-57906365fa10,यहाँ आने वाले चुनावों में हवा का रुख क्या होगा...,0,0,0.0,reject
182,04ce446d-5396-45c9-91e5-57906365fa10,ये दिखा रहा है।,0,0,0.0,reject
181,04ce446d-5396-45c9-91e5-57906365fa10,"बी जे पीएन डीए काला देश का विकास है, केरलम का ...",0,0,0.0,reject
180,04ce446d-5396-45c9-91e5-57906365fa10,कांग्रेस और लेपकिन साजिशों के बीच।,0,0,0.0,reject
177,04ce446d-5396-45c9-91e5-57906365fa10,जिसके नेता यहाँ यूथ में एस्टीमिज्म फैलाने में ...,0,0,0.0,reject
176,04ce446d-5396-45c9-91e5-57906365fa10,ये वही पीड़ित भी है।,0,0,0.0,reject
175,04ce446d-5396-45c9-91e5-57906365fa10,केरलम की शांति को भंग करना चाहते हैं कांग्रेस?...,0,0,0.0,reject
174,04ce446d-5396-45c9-91e5-57906365fa10,कांग्रेस केरल में चुनाव जीतने के लिए जमात और इ...,0,0,0.0,reject
173,04ce446d-5396-45c9-91e5-57906365fa10,जिसका नेतृत्व वो कांग्रेस कर रही है जो आप एमएम...,0,0,0.0,reject
172,04ce446d-5396-45c9-91e5-57906365fa10,एन एस सौरदगड़े यहाँ एक तरफ यूडीएफ हे।,0,0,0.0,reject
169,04ce446d-5396-45c9-91e5-57906365fa10,सबरीमाला मंदिर की लूट में भी इनकी पार्टनरशिप द...,0,0,0.0,reject
168,04ce446d-5396-45c9-91e5-57906365fa10,हैंड एस दुर्द घड़े यहाँ जब यूडीएफ की सरकार थी ...,0,0,0.0,reject
166,04ce446d-5396-45c9-91e5-57906365fa10,ये इंडस्ट्री को बर्बाद करने में भी पार्टनर है।,0,0,0.0,reject
165,04ce446d-5396-45c9-91e5-57906365fa10,डेवलपमेंट रोकने में पार्टनर है।,0,0,0.0,reject
164,04ce446d-5396-45c9-91e5-57906365fa10,फॉर्मिनलिज्म फैलाने में पार्टनर है।,0,0,0.0,reject
163,04ce446d-5396-45c9-91e5-57906365fa10,क्राइम में पार्टनर है।,0,0,0.0,reject
162,04ce446d-5396-45c9-91e5-57906365fa10,करप्शन में पार्टनर है।,0,0,0.0,reject

In [77]:
df2

,_id,doc_type,session_id,timestamp,source_text,source_text_length,translated_texts,audio_base64,audio_base64s,llm_latency_seconds,...,tts_first_token_latency_seconds,speaker_id,created_at,updated_at,total_latency,english_words_detected,total_words,english_word_ratio,is_english_by_vocab,asr_decision
26,{'$oid': '69b12e246b023d0cb6dd3731'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:03.969Z'},"नमस्कार, हम एरनाकुलम।",21,"{'malayalam': 'നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നി...",UklGRsSFBABXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsSFBABXQVZFZm10IBAAAAABAAE...,0.360,...,0.140,Guest-4,2026-03-11 14:26:04.801000+05:30,{'$date': '2026-03-11T08:56:04.801Z'},2.690,0,0,0.0,False,reject
27,{'$oid': '69b12e316b023d0cb6dd3732'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:16.565Z'},जय केरला।,9,{'malayalam': 'ജയ് കേരളം.'},UklGRhR6AgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRhR6AgBXQVZFZm10IBAAAAABAAE...,0.255,...,0.143,Guest-4,2026-03-11 14:26:17.076000+05:30,{'$date': '2026-03-11T08:56:17.076Z'},2.265,0,0,0.0,False,reject
28,{'$oid': '69b12e3e6b023d0cb6dd3733'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:29.440Z'},10 डेज़ और तगड़े।,17,"{'malayalam': '10 ദിവസത്തേക്ക് ഇത് മതിയാകും, ക...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,0.330,...,0.145,Guest-4,2026-03-11 14:26:30.136000+05:30,{'$date': '2026-03-11T08:56:30.136Z'},2.524,0,0,0.0,False,reject
29,{'$oid': '69b12e456b023d0cb6dd3734'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:36.708Z'},केरला को।,9,{'malayalam': 'കേരളത്തിലേക്ക്.'},UklGRlQvAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRlQvAQBXQVZFZm10IBAAAAABAAE...,0.193,...,0.141,Guest-4,2026-03-11 14:26:37.015000+05:30,{'$date': '2026-03-11T08:56:37.015Z'},1.999,0,0,0.0,False,reject
30,{'$oid': '69b12e4d6b023d0cb6dd3735'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:45.073Z'},"केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...",50,"{'malayalam': 'കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്,...",UklGRrSNAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRrSNAwBXQVZFZm10IBAAAAABAAE...,0.360,...,0.152,Guest-4,2026-03-11 14:26:45.767000+05:30,{'$date': '2026-03-11T08:56:45.767Z'},2.552,0,0,0.0,False,reject
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,{'$oid': '69b136786b023d0cb6dd37cd'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.563Z'},ये दिखा रहा है।,15,{'malayalam': 'അത് കാണിക്കുകയാണ്.'},UklGRsQTAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsQTAQBXQVZFZm10IBAAAAABAAE...,0.242,...,0.142,Guest-4,2026-03-11 15:01:36.852000+05:30,{'$date': '2026-03-11T09:31:36.852Z'},2.030,0,0,0.0,False,reject
183,{'$oid': '69b1367b6b023d0cb6dd37ce'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:38.339Z'},यहाँ आने वाले चुनावों में हवा का रुख क्या होगा...,91,{'malayalam': 'വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളി...,UklGRkRiBQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkRiBQBXQVZFZm10IBAAAAABAAE...,0.551,...,0.145,Guest-4,2026-03-11 15:01:39.380000+05:30,{'$date': '2026-03-11T09:31:39.380Z'},3.091,0,0,0.0,False,reject
184,{'$oid': '69b1367b6b023d0cb6dd37cf'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.910Z'},केरल में बनने वाली बीजेपी एनडीए सरकार यहाँ के ...,155,{'malayalam': 'കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള...,UklGRtTTDwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRtTTDwBXQVZFZm10IBAAAAABAAE...,1.092,...,0.141,Guest-4,2026-03-11 15:01:39.830000+05:30,{'$date': '2026-03-11T09:31:39.830Z'},5.508,0,0,0.0,False,reject
186,{'$oid': '69b136a26b023d0cb6dd37d1'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:17.570Z'},मेरे साथ बोलिए भारत माता की।,28,"{'malayalam': 'എന്നൊപ്പം ചേർന്ന് ""ഭാരത് മാതാ ...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,0.425,...,0.150,Guest-4,2026-03-11 15:02:18.279000+05:30,{'$date': '2026-03-11T09:32:18.279Z'},2.632,0,0,0.0,False,reject
187,{'$oid': '69b136ac6b023d0cb6dd37d2'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:27.622Z'},भारत माता के भारत माता के वंदे वंदे।,36,"{'malayalam': 'ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന...",UklGRjSxAgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRjSxAgBXQVZFZm10IBAAAAABAAE...,0.379,...,0.151,Guest-4,2026-03-11 15:02:28.178000+05:30,{'$date': '2026-03-11T09:32:28.178Z'},2.433,0,0,0.0,False,reject

In [78]:
sorted_df2[[
    'session_id',
    'source_text',
    'english_words_detected',
    'total_words',
    'english_word_ratio',
    'asr_decision',
    'speaker_id'
]].to_csv('sorted_df2.csv', index=False)

In [79]:
sorted_df2_upd = pd.read_csv('sorted_df2.csv')

In [8]:
df11 = sorted_df2.sort_values(by='created_at', ascending=True)
df22 = sorted_df2_upd.sort_values(by='created_at', ascending=True)
df22['asr_decision'] = df22['asr_decision'].apply(lambda x: x.lower())

NameError: name 'sorted_df2_upd' is not defined

In [115]:
df11.keys()

Index(['_id', 'created_at', 'doc_type', 'first_final_result_timestamp',
       'metadata', 'source', 'session_id', 'timestamp', 'source_text',
       'source_text_length', 'translated_texts', 'audio_base64',
       'audio_base64s', 'llm_latency_seconds', 'tts_generation_delay_seconds',
       'tts_first_token_latency_seconds', 'updated_at', 'total_latency',
       'english_words_detected', 'total_words', 'english_word_ratio',
       'is_english_by_vocab', 'asr_decision'],
      dtype='str')

In [105]:
df11["created_at"] = pd.to_datetime(df11["created_at"], utc=True)
df22["created_at"] = pd.to_datetime(df22["created_at"], utc=True)

In [116]:
out = df11[['created_at', 'source_text', 'translated_texts', 'audio_base64', 'total_latency']].merge(
    df22[['created_at', 'asr_decision']],
    on='created_at',
    how='left'
)
out['asr_decision'].value_counts()

asr_decision
accept    141
reject     57
Name: count, dtype: int64

In [80]:
# final_df = out[out['asr_decision'] == 'accept'].iloc[:-1]
final_df = df2

In [81]:
import pandas as pd

# if your table is already in df
final_df["created_at"] = pd.to_datetime(final_df["created_at"], errors="coerce")

# relative time from first valid timestamp
t0 = final_df["created_at"].dropna().min()
final_df["relative_time_s"] = (final_df["created_at"] - t0).dt.total_seconds()

# optional: pretty mm:ss
final_df["relative_time_mmss"] = pd.to_timedelta(final_df["relative_time_s"], unit="s").astype(str)
final_df = final_df.drop(columns=['relative_time_mmss'])

In [82]:
final_df

,_id,doc_type,session_id,timestamp,source_text,source_text_length,translated_texts,audio_base64,audio_base64s,llm_latency_seconds,...,speaker_id,created_at,updated_at,total_latency,english_words_detected,total_words,english_word_ratio,is_english_by_vocab,asr_decision,relative_time_s
26,{'$oid': '69b12e246b023d0cb6dd3731'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:03.969Z'},"नमस्कार, हम एरनाकुलम।",21,"{'malayalam': 'നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നി...",UklGRsSFBABXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsSFBABXQVZFZm10IBAAAAABAAE...,0.360,...,Guest-4,2026-03-11 14:26:04.801000+05:30,{'$date': '2026-03-11T08:56:04.801Z'},2.690,0,0,0.0,False,reject,0.000
27,{'$oid': '69b12e316b023d0cb6dd3732'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:16.565Z'},जय केरला।,9,{'malayalam': 'ജയ് കേരളം.'},UklGRhR6AgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRhR6AgBXQVZFZm10IBAAAAABAAE...,0.255,...,Guest-4,2026-03-11 14:26:17.076000+05:30,{'$date': '2026-03-11T08:56:17.076Z'},2.265,0,0,0.0,False,reject,12.275
28,{'$oid': '69b12e3e6b023d0cb6dd3733'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:29.440Z'},10 डेज़ और तगड़े।,17,"{'malayalam': '10 ദിവസത്തേക്ക് ഇത് മതിയാകും, ക...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,0.330,...,Guest-4,2026-03-11 14:26:30.136000+05:30,{'$date': '2026-03-11T08:56:30.136Z'},2.524,0,0,0.0,False,reject,25.335
29,{'$oid': '69b12e456b023d0cb6dd3734'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:36.708Z'},केरला को।,9,{'malayalam': 'കേരളത്തിലേക്ക്.'},UklGRlQvAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRlQvAQBXQVZFZm10IBAAAAABAAE...,0.193,...,Guest-4,2026-03-11 14:26:37.015000+05:30,{'$date': '2026-03-11T08:56:37.015Z'},1.999,0,0,0.0,False,reject,32.214
30,{'$oid': '69b12e4d6b023d0cb6dd3735'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:45.073Z'},"केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...",50,"{'malayalam': 'കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്,...",UklGRrSNAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRrSNAwBXQVZFZm10IBAAAAABAAE...,0.360,...,Guest-4,2026-03-11 14:26:45.767000+05:30,{'$date': '2026-03-11T08:56:45.767Z'},2.552,0,0,0.0,False,reject,40.966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,{'$oid': '69b136786b023d0cb6dd37cd'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.563Z'},ये दिखा रहा है।,15,{'malayalam': 'അത് കാണിക്കുകയാണ്.'},UklGRsQTAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsQTAQBXQVZFZm10IBAAAAABAAE...,0.242,...,Guest-4,2026-03-11 15:01:36.852000+05:30,{'$date': '2026-03-11T09:31:36.852Z'},2.030,0,0,0.0,False,reject,2132.051
183,{'$oid': '69b1367b6b023d0cb6dd37ce'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:38.339Z'},यहाँ आने वाले चुनावों में हवा का रुख क्या होगा...,91,{'malayalam': 'വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളി...,UklGRkRiBQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkRiBQBXQVZFZm10IBAAAAABAAE...,0.551,...,Guest-4,2026-03-11 15:01:39.380000+05:30,{'$date': '2026-03-11T09:31:39.380Z'},3.091,0,0,0.0,False,reject,2134.579
184,{'$oid': '69b1367b6b023d0cb6dd37cf'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.910Z'},केरल में बनने वाली बीजेपी एनडीए सरकार यहाँ के ...,155,{'malayalam': 'കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള...,UklGRtTTDwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRtTTDwBXQVZFZm10IBAAAAABAAE...,1.092,...,Guest-4,2026-03-11 15:01:39.830000+05:30,{'$date': '2026-03-11T09:31:39.830Z'},5.508,0,0,0.0,False,reject,2135.029
186,{'$oid': '69b136a26b023d0cb6dd37d1'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:17.570Z'},मेरे साथ बोलिए भारत माता की।,28,"{'malayalam': 'എന്നൊപ്പം ചേർന്ന് ""ഭാരത് മാതാ ...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,0.425,...,Guest-4,2026-03-11 15:02:18.279000+05:30,{'$date': '2026-03-11T09:32:18.279Z'},2.632,0,0,0.0,False,reject,2173.478
187,{'$oid': '69b136ac6b023d0cb6dd37d2'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:27.622Z'},भारत माता के भारत माता के वंदे वंदे।,36,"{'malayalam': 'ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന...",UklGRjSxAgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRjSxAgBXQVZFZm10IBAAAAABAAE...,0.379,...,Guest-4,2026-03-11 15:02:28.178000+05:30,{'$date': '2026-03-11T09:32:28.178Z'},2.433,0,0,0.0,False,reject,2183.377

In [83]:

import base64
import io
import wave
import pandas as pd
import numpy as np

def wav_duration_from_b64(s: str):
    if pd.isna(s) or not s:
        return None
    try:
        # handle possible data-URL prefix
        if "," in s and s.strip().startswith("data:"):
            s = s.split(",", 1)[1]

        audio_bytes = base64.b64decode(s)
        with wave.open(io.BytesIO(audio_bytes), "rb") as wf:
            n_frames = wf.getnframes()
            sr = wf.getframerate()
            return n_frames / float(sr) if sr else None
    except Exception:
        return None

final_df["audio_duration_s"] = final_df["audio_base64"].apply(wav_duration_from_b64)

In [84]:
final_df[['relative_time_s','total_latency', 'audio_duration_s', 'audio_base64']]

,relative_time_s,total_latency,audio_duration_s,audio_base64
26,0.000,2.690,6.72,UklGRsSFBABXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
27,12.275,2.265,3.68,UklGRhR6AgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
28,25.335,2.524,5.44,UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
29,32.214,1.999,1.76,UklGRlQvAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
30,40.966,2.552,5.28,UklGRrSNAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
...,...,...,...,...
182,2132.051,2.030,1.60,UklGRsQTAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
183,2134.579,3.091,8.00,UklGRkRiBQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
184,2135.029,5.508,23.52,UklGRtTTDwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
186,2173.478,2.632,5.44,UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...
187,2183.377,2.433,4.00,UklGRjSxAgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...

In [100]:
def compile_audio(df: pd.DataFrame, output_path: str, sample_rate: int = 22050, audio_base64_col: str = "audio_base64"):
    df = df.copy().reset_index(drop=True)
    df["desired_start_s"] = df["relative_time_s"] + df["total_latency"]

    actual_starts = []
    for i in range(len(df)):
        desired = df.loc[i, "desired_start_s"]
        if actual_starts:
            prev_end = actual_starts[-1] + df.loc[i - 1, "audio_duration_s"]
            start = max(desired, prev_end)
        else:
            start = desired
        actual_starts.append(start)

    df["actual_start_s"] = actual_starts
    df["actual_end_s"] = df["actual_start_s"] + df["audio_duration_s"]

    total_samples = int(np.ceil(df["actual_end_s"].max() * sample_rate))
    output = np.zeros(total_samples, dtype=np.int16)

    for _, row in df.iterrows():
        audio_bytes = base64.b64decode(row[audio_base64_col])
        with wave.open(io.BytesIO(audio_bytes), "rb") as wf:
            samples = np.frombuffer(wf.readframes(wf.getnframes()), dtype=np.int16)
        start = int(row["actual_start_s"] * sample_rate)
        end = min(start + len(samples), total_samples)
        output[start:end] = samples[: end - start]

    with wave.open(output_path, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sample_rate)
        wf.writeframes(output.tobytes())

    print(f"Saved {output_path} — {df['actual_end_s'].max():.2f}s, {total_samples} samples")
    return df[["desired_start_s", "actual_start_s", "audio_duration_s", "actual_end_s"]]

In [ ]:
compile_audio(final_df[['relative_time_s','total_latency', 'audio_duration_s', 'audio_base64']],"output_11_Mar_vox.wav")

Saved output_11_Mar_vox.wav — 2189.81s, 48285311 samples

     desired_start_s  actual_start_s  audio_duration_s  actual_end_s
0              2.690           2.690              6.72         9.410
1             14.540          14.540              3.68        18.220
2             27.859          27.859              5.44        33.299
3             34.213          34.213              1.76        35.973
4             43.518          43.518              5.28        48.798
..               ...             ...               ...           ...
115         2134.081        2138.875              1.60      2140.475
116         2137.670        2140.475              8.00      2148.475
117         2140.537        2148.475             23.52      2171.995
118         2176.110        2176.110              5.44      2181.550
119         2185.810        2185.810              4.00      2189.810

[120 rows x 4 columns]

In [89]:
# final_df['tamil_translated_text'] = final_df['translated_texts'].apply(lambda x: x['tamil'])
final_df['malayalam_translated_text'] = final_df['translated_texts'].apply(lambda x: x['malayalam'])

In [102]:
import requests
import base64
import io
import wave
import time

TTS_URL = "https://infer.e2enetworks.net/project/p-8848/endpoint/is-8395/tts/v3/stream_with_embedding"
TTS_HEADERS = {
    "Content-Type": "application/json",
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE3OTc1OTAzNjIsImlhdCI6MTc2NjA1NDM2MiwianRpIjoiNjkzZmYyNWQtMzI1YS00NWI4LWJkMzItMDc1MDZjZDNiM2Y1IiwiaXNzIjoiaHR0cDovL2dhdGV3YXkuZTJlbmV0d29ya3MuY29tL2F1dGgvcmVhbG1zL2FwaW1hbiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI5OGU2ZDQ0NC0xNDM2LTRkYWItYTUzZS1kMWU5MzViOWE1NzUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhcGltYW51aSIsInNlc3Npb25fc3RhdGUiOiIxNDAwMGU3MC02NzE1LTQ4ZjctYWY2Ny04M2E5NDY0NDk4MDkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjE0MDAwZTcwLTY3MTUtNDhmNy1hZjY3LTgzYTk0NjQ0OTgwOSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlRob3NoaXRoIFMiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0aG9zaGl0aEBnbmFuaS5haSIsImdpdmVuX25hbWUiOiJUaG9zaGl0aCIsImZhbWlseV9uYW1lIjoiUyIsImVtYWlsIjoidGhvc2hpdGhAZ25hbmkuYWkifQ.haroy2xNx00vPXySCfGsCs8n-r8t_v8io34uMUF-q7i19Eq3iqT0MI1T7LCb9x2xUFyNujtga8C0lOn8ADIr6BErk-r_sr9VEhB3GxCgN93--eQZSejsp8LZB1nq9IF-E6k7fL0ThV0c2p2MweAeVBuBTP0N9vy6KSNjpYlBo24"
}

SPEAKER_EMBEDDING = "AADBvAAAWzwAAJI8AABHuwAA+rwAAFe9AAAkugAANL0AALE9AAAyPQAAIr0AAL08AACTvQAAkjwAAM88AACePQAAfTwAAM28AACMPQAATT0AAIy9AABiPQAAB7wAAGw9AAD2PAAAPD0AAAY6AACqvAAAhj0AACE9AAAAvAAAoz0AABO+AAAYPQAA7j0AAGC9AABXvQAAS7wAAGA9AADNvQAABj0AAMK8AAD9PAAAWDwAALG9AABuvQAAuz0AANU9AAA1vgAAjr0AAIO8AAAuvQAAbb0AAAu9AACiPQAArjwAAEW9AABfPQAArz0AACW+AACTPQAA1L0AAEc8AAATPQAA1b0AAF+8AABWvQAA3j0AAIY8AACXPAAARrwAAJ88AABwPQAAnz0AAEo+AABVPQAAfb0AALA7AAAePgAA7LsAADq8AADQPQAA2TwAAOk8AADLvQAAKbwAACo8AAAvOwAAZD0AAAO+AACmPQAADTsAAA+9AAA9PQAAJb0AAEm7AADmPAAATb0AABa9AADoPQAAXrsAABs9AABQvAAALr0AAI49AAApPAAApDwAAKq9AACFvQAA0D0AAAA+AADrugAAHz0AAOQ9AADYvQAAE70AAC6+AACwuQAApLwAAPG7AACGPQAATDwAAJY8AAAVPAAAcT0AAJO9AACrvQAAJT4AANM9AAA2vAAAwb0AAB49AAA2PQAAWL0AADO8AAANvgAAQrwAAIS9AABTvQAA1r0AAJ+9AACgvQAAhL0AAK88AADgPAAAzLwAAJA8AACrPQAAJjsAALy7AABPvgAAxb0AADs8AAAfPQAAhzwAAN89AACnPQAA5rwAAGi9AAArPQAAtLwAAHO9AADLPQAAMjwAAIO9AACrvAAAzj0AAFU8AADhOgAAAT0AAN88AACSPAAAYb0AAIQ8AACmvQAAE74AAOq8AAAiPgAA2TwAAIY8AAAKvQAAYbwAAIg8AACTvQAAKD0AAIE9AABAPAAA5T0AANW9AADYPQAAXzwAAKC8AAAYvQAArr0AAE08AAARuwAAhj0AANI8AABSvQAAgj0AAEs8AAAqvAAAHb4AALu9AAAWvQAAab0AAJ69AAAaPQAAI7wAALu9AAAlPQAAzToAADg8AAAuvAAA270AAIK9AABmuwAASr0AAHm9AAAaPQAAzT0AAJy8AAD+vAAAijwAAI49AACdPAAAij0AANU7AACQvQAAGr4AAD+9AABTvgAAo7wAAJY9AAC2vQAATTwAACQ7AADMPAAAAzsAADk6AADCvQAAhz0AAA88AABhPQAAs7sAADI9AAAOvQAABD4AAJc8AACzPAAAhr0AABw9AACJPQAAtrsAAI89AAAwvQAAmL0AAAO+AACSvQAAFL4AAPs8AAAOvgAAsD0AAKy9AAB3PAAA1jwAAPG9AACtvAAArD0AAFw8AACuPQAABr4AABC+AAAMvgAA4T0AAAU9AACKPQAAvzwAABI+AAC0vAAAdT0AABC8AAARvAAANT0AACC9AACqvQAAZ70AAGU7AACYPQAA5T0AAHw8AAAEPAAAIb0AAOs9AABKPQAApD0AAE69AAClOwAAZjwAACs9AABAPAAAVL0AAB29AAB2PAAAWr0AAA29AAACPQAA8DwAAKY9AABLPQAAUj0AAIm8AAAevQAAUjwAACq9AAC+vQAAzzwAAJ49AACKPQAA2z0AAOu8AACQPAAALD0AAKg5AABDvQAAdb0AAKW9AABmPQAAy70AAGg7AAD/vAAApbwAAD8+AACOvQAAEz4AAOS8AAAzPAAASz0AADW+AADLOgAAhb0AAOw8AADVvQAA+L0AACS9AABnvQAApT0AAJ89AAD5OwAAMD0AABG8AAC0ugAAST0AAOa9AACIPQAA6T0AAN49AACDvAAAIz0AAME7AAAlPQAAkD0AAH+9AABOPQAAuz0AAF+9AAA3ugAAv70AADc9AAAePQAAyL0AAPS7AACtPQAAjDwAAG28AADfvQAAE70AAN49AAB4vQAA0r0AAEq8AAB4vgAAAT4AAGw9AADuPAAATDwAALm8AABVPQAAnzwAACE9AAC+PAAASL0AAJ+9AAA1vgAAVbwAAJI9AACTvQAAhz0AABW9AAB5vQAAET0AAPQ9AACOPAAAYz0AADg9AADyvAAAKTsAALg9AAAKvgAAerwAAOA9AAAVOwAA0L0AAH28AAARPgAAELwAAMG8AABTvQAA0LoAADM9AADBvQAAsT0AAMm9AACRvQAAAb0AAL+9AADjvAAAsrwAADW7AACrvAAAqb0AAIW8AADUvQAAWTwAAJk9AAD7vAAAEj4AAKI9AABiPAAAi70AAOm8AADiPQAAoDkAAHA9AABQvQAAaDsAAJm8AAAHvQAA9r0AADg+AABMvQAAvD0AAFc8AACXvQAAtr0AAOc9AADQvgAAkrwAAJW9AACpPAAAsz0AAPm8AACWOwAATTwAAIU9AACMPQAALTwAAA49AAALvQAAa70AAAa8AAARPQAAm70AAI+9AAABPQAAmzwAAJ49AAAGPAAAZT0AAEO9AAC9vQAAqz0AANg8AACsvAAAljwAALi8AABqPQAAvr0AADI8AACMvAAAhz0AAL49AAAivQAAhb0AAPU7AACIvQAAbzwAAEY9AADQPAAAhj0AAMI8AABEvQAApD0AAAW9AACDPQAAjj0AAKU8AACkPAAAOb0AAMI7AAC7vQAAsT0AABa+AACkPQAA3TsAADs9AADlPAAABTsAAJW9AAB+vQAAgj0AANo9AAA2vgAAwDwAADk9AACjvQAAhz0AAOa9AADpvAAAtL0AAIo9AAB2vQAAnjwAAAg8AAB1PQAAhTwAAAm9AADbuwAA4LsAABc8AACOvQAALLwAAMy9AABFvgAAljsAAB4+AAAxPAAA77wAAGm9AABYPQAAsz0AAAq9AAD6OQAAij0AAKm7AADavQAAWzsAAN08AAAdPAAAhDwAAEO+AACXvQAAh7wAADC+AAD3PQAA1z0AAMW7AABcPAAARDwAAIa9AAD9PAAAQ70AANE9AABxPQAA1L0AAAC9AADJPQAAWT0AACg8AAAkvQAAIT0AAI69AADfvQAAuDsAAMO9AACCPQAALDwAAKo8AABRvAAAfj4AALm9AADVvQAA2D0AACY9AABdvQAA/D0AAMs9AADXPAAAFD0AACW9AACIvAAA3bwAAOE9AABlPQAAVj4AAPe8AADpPQAAk70AAIk8AACGPQAAtzwAAIS9AAApPQAAAb0AACY9AABkvAAAvb0AAKg9AAAHvgAAhz0AAKM9AAAeuwAA8b0AACY+AADgvQAAqD0AAGI9AADIPQAA77wAAJ68AAAdPgAA7T0AAMo9AAALOwAA87wAAH28AABpPQAAzr0AABs+AACsvQAAij0AALY9AAChuwAAxD0AADy8AAAlPQAAuL0AAMe9AACPvAAAGj4AACG9AACiPQAAszwAAOQ5AAAVPAAAhT0AAK+8AAB7vQAAU70AAM+9AACZPQAArbsAALy9AABnPQAAVD0AAMG9AACkOgAAaT0AAH+9AAAhvQAAlL0AANQ9AABUPQAAbb0AAFi9AAAYPgAAST0AANq5AABfPAAALj0AACu9AACzPAAAUT0AAGc8AAB4PQAAjj0AADI+AABuPQAAgL0AAJu8AAB9vQAAED4AAP09AAAtvQAAoL0AADk9AABqvQAADrsAAEg9AACevQAArT0AAEa9AACJvQAAwLkAAP+8AAAovAAAlDwAAAs9AACpvAAA4TwAAJM8AABUvAAAHTkAAPO8AAA8PQAAlb0AABq+AAC9PAAAM70AAP69AABBPQAADDwAANe8AAAKvgAAKj0AANu9AAAUvgAA5L0AAFG9AAC9PQAADL0AAG29AACgPQAA2LwAACM9AAAWOwAAGDoAAKw9AAAJPQAApbsAAEI9AADdPAAAab0AAKi9AADAPQAAIj4AAN07AAAJPgAAoDwAAIO9AAB7PQAA87gAAOu9AAADvgAAFL0AAAy9AAD8PAAAZr0AAAQ9AAAJPgAAj7sAALI9AABbPQAAvT0AALC9AAB4PQAARDsAANI9"

SAMPLE_RATE = 8000

def raw_pcm_to_wav_b64(raw_bytes: bytes, sample_rate: int = 24000) -> str:
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sample_rate)
        wf.writeframes(raw_bytes)
    return base64.b64encode(buf.getvalue()).decode()

def call_tts(text: str) -> str:
    payload = {
        "text": text,
        "speaker_embedding": {
            "embedding": SPEAKER_EMBEDDING,
            "shape": [1, 768],
            "dtype": "torch.bfloat16"
        },
        "sample_rate": SAMPLE_RATE,
        "format": "pcm16"
    }
    resp = requests.post(TTS_URL, headers=TTS_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return raw_pcm_to_wav_b64(resp.content, SAMPLE_RATE)

new_audio_b64 = []
itr = 0
for idx, row in final_df.iterrows():
    text = row["malayalam_translated_text"]
    print(f"[{len(new_audio_b64)+1}/{len(final_df)}] {text[:60]}...")
    # itr +=1
    try:
        b64 = call_tts(text)
        new_audio_b64.append(b64)
        print(f"  -> got {len(b64)} chars of base64")
    except Exception as e:
        print(f"  -> FAILED: {e}")
        new_audio_b64.append(None)
   
    # time.sleep(0.1)

final_df["audio_base64_malayalam"] = new_audio_b64
final_df["audio_duration_s"] = final_df["audio_base64_malayalam"].apply(wav_duration_from_b64)
print(f"\nDone! {sum(1 for x in new_audio_b64 if x)} / {len(new_audio_b64)} succeeded")

[1/120] നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നിന്നാണ്....
  -> got 49620 chars of base64
[2/120] ജയ് കേരളം....
  -> got 29832 chars of base64
[3/120] 10 ദിവസത്തേക്ക് ഇത് മതിയാകും, കൂടുതൽ ആവശ്യമില്ല....
  -> got 77872 chars of base64
[4/120] കേരളത്തിലേക്ക്....
  -> got 22392 chars of base64
[5/120] കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്, നിങ്ങളുടെ മനസ്സിലെ ആഗ്രഹമായി...
  -> got 84032 chars of base64
[6/120] ഇപ്പോൾ ഈ മഹത്തായ സംസ്ഥാനത്തെക്കുറിച്ച് രാജ്യവും ലോകവും അറിയു...
  -> got 163612 chars of base64
[7/120] കേരളം എന്ന് വിളിക്കുന്നു....
  -> got 31288 chars of base64
[8/120] അതിലൂടെ എനിക്ക് അഭിമാനമുണ്ട്....
  -> got 52648 chars of base64
[9/120] ചരിത്രപരമായ ഒരു നേട്ടം കൂടിയാണ് ഇത്....
  -> got 57240 chars of base64
[10/120] ബി.ജെ.പി.-എൻ.ഡി.എ സർക്കാർ ഇത് ചെയ്തിട്ടുണ്ട്....
  -> got 67396 chars of base64
[11/120] ഇത് നിങ്ങളുടെ വികാരങ്ങളെ മാനിക്കുന്നതിനെക്കുറിച്ചാണ്....
  -> got 64960 chars of base64
[12/120] ഇതൊരു മികച്ച മലയാളിയൻ പൈതൃകത്തിന്റെ ആദരവ് കൂടിയാണ്....
  -> got 82696 chars of base64
[13/120] ഹാൻഡ്‌സൗർഡോഗ്....
  -> got 32568 chars of base64
[14/120] ഇരുപത്തിയൊന്നാം നൂറ്റാണ്ടിന്റെ ഈ കാലം....
  -> got 61480 chars of base64
[15/120] കേരളത്തിന് ഇത് വളരെ നിർണായകമായ ഒരു കാലഘട്ടമാണ്. കേരളത്തിന് ഒ...
  -> got 163720 chars of base64
[16/120] ഒരു പുതിയ തുടക്കം വേണം. കേരളത്തിലെ ജനങ്ങൾ എൽഡിഎഫും യുഡിഎഫും ...
  -> got 215000 chars of base64
[17/120] ഈ വലിയ പൊതുയോഗത്തിലും അതുതന്നെയായിരുന്നു....
  -> got 53880 chars of base64
[18/120] അതൊരു വ്യക്തമായ ആത്മവിശ്വാസമാണ്, അത് വ്യക്തമായി കാണാൻ സാധിക്...
  -> got 85608 chars of base64
[19/120] ഫിസ്സൂർ ജില്ലയിലെ ജനങ്ങൾ....
  -> got 60300 chars of base64
[20/120] തിരുവനന്തപുരം ജില്ലയിലെ ജനങ്ങൾ....
  -> got 50120 chars of base64
[21/120] കേരളത്തിലെ നിരവധി പഞ്ചായത്തുകളിൽ, ജനങ്ങൾ ബിജെപി-എൻഡിഎയ്‌ക്ക്...
  -> got 150488 chars of base64
[22/120] നിങ്ങൾ കാണിച്ച വിശ്വാസമാണ്, ഈ പദ്ധതി പൂർണ്ണമായി വിജയകരമാക്കാ...
  -> got 100692 chars of base64
[23/120] കേരളത്തിന്റെ വളർച്ച, ഇടതുപക്ഷ ജനാധിപത്യ മുന്നണി (എൽഡിഎഫ്) സർ...
  -> got 192576 chars of base64
[24/120] എൻഡിഎസ്, ഉദഗഡെ കെറം എന്നിവയ്ക്ക് പ്രകൃതി, സംസ്കാരം, കഴിവുകൾ,...
  -> got 247560 chars of base64
[25/120] ഒരിക്കൽ യുഡിഎഫ് സർക്കാരിന്റെ നയങ്ങൾ കേരളത്തിന് വലിയ നാശനഷ്ടമ...
  -> got 118196 chars of base64
[26/120] ഈ രണ്ട് ഗ്രൂപ്പുകളും 510 വർഷങ്ങൾക്ക് ശേഷം തങ്ങൾക്ക് അവസരം ലഭ...
  -> got 329992 chars of base64
[27/120] അവ തടയപ്പെടുന്നു....
  -> got 34716 chars of base64
[28/120] എൻഡിഎസ് സൗരദണ്ഡം....
  -> got 36036 chars of base64
[29/120] കേരളത്തിന്റെ അതിവേഗ വളർച്ചയ്ക്കായി ഒരു കൈത്താഴ്വ്....
  -> got 70080 chars of base64
[30/120] നിലവിലെ രീതി മാറ്റേണ്ടത് അത്യാവശ്യമാണ്. അതിനാൽ, ഇത്തവണ ഇവിടെ...
  -> got 151956 chars of base64
[31/120] നിങ്ങൾ കോൺഗ്രസ്സിനും, ലെപ്പിനും 70 വർഷത്തിലേറെയായി സേവനം നൽക...
  -> got 101768 chars of base64
[32/120] ഇനി വരുന്ന അഞ്ച് വർഷത്തേക്ക് ബി.ജെ.പി.-ക്ക് അവസരം നൽകുക. വിക...
  -> got 173964 chars of base64
[33/120] നിങ്ങൾക്ക് മോഡിയുടെ ഉറപ്പ് ഉണ്ട്....
  -> got 54328 chars of base64
[34/120] ഇതുവരെ നിറഞ്ഞിട്ടില്ലാത്തത്....
  -> got 31004 chars of base64
[35/120] നിങ്ങൾ മാറുന്നു, കേരളം മുന്നോട്ട് പോകുന്നു....
  -> got 54944 chars of base64
[36/120] അമ്മ തജ്‌മറുമായി ഒരു കരാർ ഉണ്ടാക്കി....
  -> got 52632 chars of base64
[37/120] ഇന്ന്, വികസിത കിരണത്തിനായി ബിജെപി എൻഡിഎയുടെ പ്രചാരണ പരിപാടിക...
  -> got 126952 chars of base64
[38/120] ബിജെപി-എൻഡിഎയുടെ കാഴ്ചപ്പാടാണ് ഇത്. ആരോഗ്യത്തിനും വിനോദസഞ്ചാ...
  -> got 151848 chars of base64
[39/120] വിവാഹത്തിനായി കേരളം ഒരു മികച്ച സ്ഥലമായി തിരഞ്ഞെടുക്കപ്പെടാൻ ...
  -> got 359492 chars of base64
[40/120] കേന്ദ്ര സർക്കാർ നടപ്പാക്കുന്ന പദ്ധതികൾ തടസ്സങ്ങളില്ലാതെ പൂർത...
  -> got 96680 chars of base64
[41/120] വികസിത കേരളത്തിനായി....
  -> got 44760 chars of base64
[42/120] ഏറ്റവും വലിയ ആവശ്യം എന്താണ്?...
  -> got 38948 chars of base64
[43/120] സഞ്ചാരിത?...
  -> got 56536 chars of base64
[44/120] മികച്ച പ്രതിഭയുള്ളവരെ കണ്ടെത്തുകയും, അത്യാധുനിക സാങ്കേതികവിദ...
  -> got 142336 chars of base64
[45/120] എന്നാൽ 20-ാം നൂറ്റാണ്ടിന്റെ ആദ്യ 25 വർഷങ്ങളിൽ എൽഡിഎഫും യുഡിഎ...
  -> got 312116 chars of base64
[46/120] അതല്ല. കേരളത്തിലെ ആളുകൾ കണ്ടറിഞ്ഞിട്ടുണ്ട്, കോണ്‍ഗ്രസിന്റെ യ...
  -> got 293464 chars of base64
[47/120] ഇന്ത്യയിൽ ഇന്ന് നിരവധി കമ്പനികൾ ഡ്രോണുകൾ നിർമ്മിക്കുന്നുണ്ട്...
  -> got 308080 chars of base64
[48/120] കർണത്തിലെ യുവാക്കളുടെ കഴിവ് അവന് ഒരിക്കലും മനസ്സിലാവില്ല. പ്...
  -> got 132472 chars of base64
[49/120] ബിജെപി-എൻഡിഎ കേരളത്തിലെ കഴിവുള്ളവരെ പരിഗണിക്കുകയും അവർക്ക് അ...
  -> got 332596 chars of base64
[50/120] ഇത്തരം എല്ലാ തടസ്സങ്ങളും ബിജെപി നേതൃത്വത്തിലുള്ള എൻഡിഎ സർക്ക...
  -> got 366472 chars of base64
[51/120] ഫിഷർ ബാങ്ക് കമ്മ്യൂണിറ്റിയുടെ വളർച്ചയാണ് ഞങ്ങളുടെ പ്രധാന ലക്...
  -> got 87636 chars of base64
[52/120] കഴിഞ്ഞ 11 വർഷത്തിനുള്ളിൽ, മത്സ്യ ഉൽപാദനത്തിൽ ഇന്ത്യ ലോകത്തില...
  -> got 149284 chars of base64
[53/120] കേന്ദ്രത്തിലെ ബിജെപി സർക്കാർ മത്സ്യത്തൊഴിലാളികൾക്കായി ചെയ്യേ...
  -> got 339660 chars of base64
[54/120] കടപ്പത്രം അനുവദിച്ചിട്ടുണ്ട്. ബി.ജെ.പി-യുടെ കേന്ദ്ര സർക്കാർ ...
  -> got 380784 chars of base64
[55/120] ആൻഡ് സൗരദഗഢിൽ, മറ്റൊരു വിഷയത്തെക്കുറിച്ച് ഇന്ന് ഞാൻ നിങ്ങളുമ...
  -> got 136820 chars of base64
[56/120] ഗൾഫ് മേഖലയിലും പശ്ചിമേഷ്യയിലും നടക്കുന്ന സംഭവങ്ങളെക്കുറിച്ച്...
  -> got 156260 chars of base64
[57/120] നമ്മുടെ ലക്ഷക്കണക്കിന് സഹോദരീ സഹോദരന്മാർ അവിടെ ജോലി ചെയ്യുന്...
  -> got 182656 chars of base64
[58/120] ഞങ്ങളുടെ രാജ്യത്തിലെ ഏതൊരു പൗരനും ദുരിതത്തിൽ അകപ്പെട്ടാൽ, അവ...
  -> got 162920 chars of base64
[59/120] ഇറാഖിൽ കുടുങ്ങിയ നഴ്സുമാരെ രക്ഷപ്പെടുത്തുന്നതിനെക്കുറിച്ച് സ...
  -> got 111040 chars of base64
[60/120] യെമനിലെ ഭീകരവാദികളുടെ തടവിൽ നിന്ന് ഫാദർ ടോമിനെ രക്ഷപ്പെടുത്ത...
  -> got 124132 chars of base64
[61/120] ഇന്നത്തെ ഇന്ത്യ, തന്റെ പൗരന്മാർക്ക് ദുരിതഘട്ടങ്ങളിൽ ഒറ്റയ്ക്...
  -> got 136380 chars of base64
[62/120] ഫാദർ അലക്സിസ് പ്രേം കുമാറിനെയും ഞങ്ങൾ അഫ്ഗാനിസ്ഥാനിൽ നിന്ന് ...
  -> got 140408 chars of base64
[63/120] ഇന്നും യുദ്ധഭൂമിയിൽ കുടുങ്ങിയ ഇന്ത്യക്കാരെ സുരക്ഷിതരായി നാട്...
  -> got 189828 chars of base64
[64/120] ഗൾഫ് മേഖലയിലെ നമ്മുടെ എല്ലാ സൗഹൃദ രാജ്യങ്ങളിലെ സർക്കാരുകളും ...
  -> got 231868 chars of base64
[65/120] ഓരോ രാജ്യത്തും ഞങ്ങളുടെ എംബസികൾ ഉണ്ട്....
  -> got 55028 chars of base64
[66/120] ഞങ്ങളുടെ ലക്ഷ്യം ഇതാണ്....
  -> got 48476 chars of base64
[67/120] അവർ 24 മണിക്കൂറും അവരെ പരിചരിക്കുന്നു. എല്ലാവരും ഭക്ഷണം കഴിക...
  -> got 113536 chars of base64
[68/120] ആരോഗ്യ സംരക്ഷണവും, നിയമപരമായ സഹായവും ഉൾപ്പെടെയുള്ള എല്ലാ സഹാ...
  -> got 168252 chars of base64
[69/120] ഇത്ര വലിയ ഒരു ആഗോള പ്രതിസന്ധിയിലും കോണ്‍ഗ്രസ് പാര്‍ട്ടി രാഷ്...
  -> got 120072 chars of base64
[70/120] കോൺഗ്രസ് പാർട്ടി മനഃപൂർവ്വം ചെയ്തതാണ്....
  -> got 73348 chars of base64
[71/120] പ്രകോപനപരമായ പ്രസ്താവനകൾ നടത്തുന്നു, ഉത്തരവാദിത്തമില്ലാത്ത പ...
  -> got 106096 chars of base64
[72/120] വിജയം നിങ്ങളെ അഹങ്കാരിയാക്കരുത്....
  -> got 54664 chars of base64
[73/120] അവരുടെ ആളുകൾ അവിടെ ദുരിതത്തിൽ അകപ്പെട്ടാൽ, പിന്നീട് അവർ ഒത്ത...
  -> got 188680 chars of base64
[74/120] ഗൾഫിൽ നടക്കുന്ന യുദ്ധത്തിൽ ഞങ്ങൾ പങ്കാളികളാണ്....
  -> got 70428 chars of base64
[75/120] സ്വയംപര്യാപ്തതയുടെ പ്രാധാന്യവും വീണ്ടും ഉയർത്തിക്കാട്ടുന്നു....
  -> got 87204 chars of base64
[76/120] വിശദീകരിച്ചിരിക്കുന്നു....
  -> got 29816 chars of base64
[77/120] ഊർജ്ജം ആകട്ടെ, അല്ലെങ്കിൽ മറ്റ് ഏത് മേഖല ആകട്ടെ....
  -> got 67128 chars of base64
[78/120] ഇന്ത്യ എല്ലാ മേഖലകളിലും സ്വയംപര്യാപ്തത നേടാൻ ശ്രമിക്കുകയാണ്....
  -> got 91464 chars of base64
[79/120] സ്വയംപര്യാപ്തരാകുന്നത് എത്രത്തോളം പ്രധാനമാണ്?...
  -> got 71996 chars of base64
[80/120] ഞങ്ങൾ ഇത് കൊറോണക്കാലത്ത് കണ്ടതാണ്....
  -> got 53344 chars of base64
[81/120] ഉക്രെയ്ൻ പ്രതിസന്ധിയുടെ സമയത്ത് ഇത് കണ്ടു....
  -> got 76896 chars of base64
[82/120] നിലവിലെ പ്രതിസന്ധി ഒരിക്കൽ കൂടി സ്വയംപര്യാപ്തത എത്രത്തോളം പ്...
  -> got 121012 chars of base64
[83/120] എൻഡിഎസ് സൗരഭ്, ഊർജ്ജമേഖലയിൽ മറ്റ് രാജ്യങ്ങളെ ആശ്രയിക്കുന്നത്...
  -> got 140888 chars of base64
[84/120] കഴിഞ്ഞ കുറച്ച് വർഷങ്ങളായി സ്ഥിരമായ രീതിയിൽ മുന്നോട്ട് പോയ പ്...
  -> got 186724 chars of base64
[85/120] ഇന്ത്യയിൽ കുറച്ചുകാലം മുൻപ്, കേരളത്തിലും ഒരു സോളാർ പദ്ധതിയുട...
  -> got 340828 chars of base64
[86/120] അത് ഒരു സുരക്ഷിത സ്ഥലമാണ്....
  -> got 46776 chars of base64
[87/120] ഒരു ഭാഗത്ത്....
  -> got 23464 chars of base64
[88/120] ബിജെപി നേതൃത്വത്തിലുള്ള എൻഡിഎ രാജ്യത്തെ ആത്മനിർഭരമാക്കാൻ നിര...
  -> got 296340 chars of base64
[89/120] കോൺഗ്രസും ഇടതുപക്ഷവും ഒരുമിച്ച് ചേർന്ന് സർക്കാരുകൾ രൂപീകരിച്...
  -> got 114948 chars of base64
[90/120] ഇവരാൽ രാജ്യത്തെ കൂടുതൽ വിദേശ രാജ്യങ്ങളെ ആശ്രയിക്കാൻ നിർബന്ധി...
  -> got 106960 chars of base64
[91/120] ഇന്ന് ഈ ആളുകൾ ഒത്തുചേർന്ന് സംസാിക്കുന്നത് കാണുക....
  -> got 79368 chars of base64
[92/120] ഇന്ന് യുദ്ധകാലം....
  -> got 33672 chars of base64
[93/120] ഈ സമയത്തും....
  -> got 57984 chars of base64
[94/120] കോൺഗ്രസ്സിന്റെ സ്വാധീനവും അതിന്റെ അനുബന്ധ സംവിധാനങ്ങളും രാജ്...
  -> got 113048 chars of base64
[95/120] പൂർണ്ണ ശക്തിയോടെ അച്ചടിക്കുന്നു....
  -> got 50980 chars of base64
[96/120] ഞാൻ രാജ്യത്തിലെ ജനങ്ങളോട് പറയുന്നതാണ്....
  -> got 64024 chars of base64
[97/120] കോൺഗ്രസ്, ഇടതുപക്ഷം, കൂടാതെ ഇവരുമായി ബന്ധപ്പെട്ട മറ്റ് സംഘടന...
  -> got 153312 chars of base64
[98/120] പരത്തുന്ന വ്യാജ വാർത്തകളിൽ ശ്രദ്ധയുണ്ടായിരിക്കുക, ജാഗ്രത പാല...
  -> got 84328 chars of base64
[99/120] അതുപോലെ തന്നെ, ഗണേഷനോട് ക്ഷേമമറിയിക്കുക....
  -> got 65952 chars of base64
[100/120] എൽഡിഎഫ് ആണെങ്കിലും യുഡിഎഫ് ആണെങ്കിലും, അവയുടെ പേരുകൾ വ്യത്യസ...
  -> got 147320 chars of base64
[101/120] അദ്ദേഹം അതിൽ പങ്കാളിയാണ്....
  -> got 42904 chars of base64
[102/120] അയാൾ കുറ്റകൃത്യത്തിൽ പങ്കാളിയാണ്....
  -> got 54528 chars of base64
[103/120] ഫോർമാലിസം പ്രചരിപ്പിക്കുന്നതിൽ പങ്കാളിയുണ്ട്....
  -> got 67312 chars of base64
[104/120] വികസനം തടസ്സപ്പെടുത്തുന്നതിൽ പങ്കാളിയാണ് അവൾ....
  -> got 67296 chars of base64
[105/120] ഈ വ്യവസായത്തെ തകർക്കാൻ സഹായിക്കുന്ന ഒരാളാണ് ഇയാൾ....
  -> got 78352 chars of base64
[106/120] യുഡിഎഫ് സർക്കാരിന്റെ കാലത്ത് സോളാർ വിവാദത്തെക്കുറിച്ചാണ് എല്...
  -> got 106328 chars of base64
[107/120] സബരിമല ക്ഷേത്രത്തിലെ കവർച്ചയിൽ ഇവരുടെ പങ്കാളിത്തം ശ്രദ്ധിക്ക...
  -> got 278496 chars of base64
[108/120] എൻ.എസ്. സൗരദഗഢെ ഇവിടെ ഒരുവശത്ത് യുഡിഎഫ് ഉണ്ട്....
  -> got 87148 chars of base64
[109/120] അവർ നേതൃത്വം നൽകുന്നത് കോണ്‍ഗ്രസ്സിന് ആണ്, അത് ഇപ്പോൾ മുസ്‌ല...
  -> got 151020 chars of base64
[110/120] കേരളത്തിൽ തിരഞ്ഞെടുപ്പിൽ വിജയിക്കാൻ, ജമാഅത്ത് ഉൾപ്പെടെയുള്ള ...
  -> got 292952 chars of base64
[111/120] കേരളത്തിലെ സമാധാനത്തെ തകർക്കാൻ കോൺഗ്രസ് ശ്രമിക്കുകയാണോ? എംഎം...
  -> got 245024 chars of base64
[112/120] അയാൾ തന്നെയാണ് ഇര കൂടിയായത്....
  -> got 35344 chars of base64
[113/120] ഇവിടെ യുവജനങ്ങളിലേക്ക് വർഗീയ വികാരം പടർത്തുന്നതിൽ മുൻപന്തിയി...
  -> got 232120 chars of base64
[114/120] കോൺഗ്രസും ലെപ്കിനും തമ്മിലുള്ള ഗൂഢാലോചനകൾ....
  -> got 70872 chars of base64
[115/120] ബിജെപി, എൻഡിഎ എന്നിവ ഇന്ത്യയുടെയും കേരളത്തിന്റെയും വികസനത്തി...
  -> got 113488 chars of base64
[116/120] അത് കാണിക്കുകയാണ്....
  -> got 43768 chars of base64
[117/120] വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളിൽ രാഷ്ട്രീയ കാലാവസ്ഥ എങ്ങനെയാ...
  -> got 143140 chars of base64
[118/120] കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള്ള എൻഡിഎ സർക്കാർ അധികാരത്തിൽ ...
  -> got 317896 chars of base64
[119/120] എന്നൊപ്പം ചേർന്ന് "ഭാരത് മാതാ കി ജയ്" എന്ന് വിളിക്കുക....
  -> got 76008 chars of base64
[120/120] ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന് ജയ്....
  -> got 81712 chars of base64

Done! 120 / 120 succeeded

In [93]:
b64_audio = call_tts("ഇപ്പോൾ ഈ മഹത്തായ സംസ്ഥാനത്തെക്കുറിച്ച് രാജ്യവും ലോകവും അറിയുന്നത് എനിക്ക് വലിയ അഭിമാനകരമായ കാര്യം ആണ്.")
with open("example_malayalam.wav", "wb") as f:
    f.write(base64.b64decode(b64_audio))

In [107]:
compile_audio(
    final_df.assign(total_latency=0)[["relative_time_s", "total_latency", "audio_duration_s", "audio_base64_malayalam"]][:],
    "output_11_Mar_malayalam_magpie.wav",
    audio_base64_col="audio_base64_malayalam",
    sample_rate=8000
)

Saved output_11_Mar_malayalam_magpie.wav — 2187.20s, 17497635 samples

     desired_start_s  actual_start_s  audio_duration_s  actual_end_s
0              0.000        0.000000          2.323125      2.323125
1             12.275       12.275000          1.395625     13.670625
2             25.335       25.335000          3.647500     28.982500
3             32.214       32.214000          1.046750     33.260750
4             40.966       40.966000          3.936125     44.902125
..               ...             ...               ...           ...
115         2132.051     2135.358125          2.048750   2137.406875
116         2134.579     2137.406875          6.706875   2144.113750
117         2135.029     2144.113750         14.898625   2159.012375
118         2173.478     2173.478000          3.560125   2177.038125
119         2183.377     2183.377000          3.827375   2187.204375

[120 rows x 4 columns]

In [110]:
compile_audio(
    final_df.assign(total_latency=0)[["relative_time_s", "total_latency", "audio_duration_s", "audio_base64_malayalam"]][:],
    "output_11_Mar_malayalam_magpie.wav",
    audio_base64_col="audio_base64_malayalam",
    sample_rate=8000
)

Saved output_11_Mar_malayalam_magpie.wav — 2187.20s, 17497635 samples

     desired_start_s  actual_start_s  audio_duration_s  actual_end_s
0              0.000        0.000000          2.323125      2.323125
1             12.275       12.275000          1.395625     13.670625
2             25.335       25.335000          3.647500     28.982500
3             32.214       32.214000          1.046750     33.260750
4             40.966       40.966000          3.936125     44.902125
..               ...             ...               ...           ...
115         2132.051     2135.358125          2.048750   2137.406875
116         2134.579     2137.406875          6.706875   2144.113750
117         2135.029     2144.113750         14.898625   2159.012375
118         2173.478     2173.478000          3.560125   2177.038125
119         2183.377     2183.377000          3.827375   2187.204375

[120 rows x 4 columns]

In [56]:
# final_df[['created_at','source_text','tamil_translated_text']].to_csv('final_df_1.csv', index=False)
# final_df[['created_at','source_text','malayalam_translated_text']].to_csv('final_df_11Mar.csv', index=False)
final_df[['created_at','source_text','malayalam_translated_text']]

SyntaxError: unmatched ')' (1402631259.py, line 3)

In [64]:
export_df = final_df[['created_at','source_text','malayalam_translated_text']].copy()
for col in export_df.select_dtypes(include=["datetimetz"]).columns:
    export_df[col] = export_df[col].dt.tz_convert('Asia/Kolkata').dt.tz_localize(None)
export_df.to_excel('final_df_11Mar.xlsx', index=False)

In [ ]:
final_df

26     {'malayalam': 'നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നി...
27                           {'malayalam': 'ജയ് കേരളം.'}
28     {'malayalam': '10 ദിവസത്തേക്ക് ഇത് മതിയാകും, ക...
29                      {'malayalam': 'കേരളത്തിലേക്ക്.'}
30     {'malayalam': 'കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്,...
                             ...
182                  {'malayalam': 'അത് കാണിക്കുകയാണ്.'}
183    {'malayalam': 'വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളി...
184    {'malayalam': 'കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള...
186    {'malayalam': 'എന്നൊപ്പം ചേർന്ന് "ഭാരത് മാതാ ...
187    {'malayalam': 'ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന...
Name: translated_texts, Length: 120, dtype: object

In [1]:
with open("mar_11_logs.txt") as f:
    transcripts_log = f.read()

In [2]:
transcripts_log.split("\n")

['2026-03-11 07:39:01.309 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | केरल',
 '2026-03-11 07:39:01.710 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | केरल में',
 '2026-03-11 07:39:03.308 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी',
 '2026-03-11 07:39:03.809 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार',
 '2026-03-11 07:39:04.110 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा',
 '2026-03-11 07:39:04.709 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुन',
 '2026-03-11 07:39:05.104 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस',
 '2026-03-11 07:39:05.406 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्म',
 '2026-03-11 07:39:05.708 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग',
 '2026-03-11 07:39:06.010 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम',
 '2026-03-11 07:39:06.321 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को',
 '2026-03-11 07:39:06.504 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोम',
 '2026-03-11 07:39:06.614 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट',
 '2026-03-11 07:39:07.008 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया',
 '2026-03-11 07:39:07.209 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा',
 '2026-03-11 07:39:07.510 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है',
 '2026-03-11 07:39:08.906 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | तटी',
 '2026-03-11 07:39:09.407 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है तटीय',
 '2026-03-11 07:39:09.508 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | तटीय क्षेत्र',
 '2026-03-11 07:39:09.609 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | तटीय क्षेत्रों',
 '2026-03-11 07:39:09.810 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | तटीय क्षेत्रों तक',
 '2026-03-11 07:39:10.211 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजना',
 '2026-03-11 07:39:10.505 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं',
 '2026-03-11 07:39:10.606 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का',
 '2026-03-11 07:39:10.807 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ',
 '2026-03-11 07:39:11.108 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचा',
 '2026-03-11 07:39:11.309 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने',
 '2026-03-11 07:39:11.610 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए',
 '2026-03-11 07:39:13.213 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सा',
 '2026-03-11 07:39:13.406 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर',
 '2026-03-11 07:39:13.507 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र',
 '2026-03-11 07:39:15.304 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | और',
 '2026-03-11 07:39:15.605 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत',
 '2026-03-11 07:39:15.907 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य',
 '2026-03-11 07:39:16.108 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा',
 '2026-03-11 07:39:16.410 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र',
 '2026-03-11 07:39:16.611 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का',
 '2026-03-11 07:39:17.212 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क',
 '2026-03-11 07:39:17.313 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी',
 '2026-03-11 07:39:17.605 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया',
 '2026-03-11 07:39:17.906 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया',
 '2026-03-11 07:39:19.510 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके',
 '2026-03-11 07:39:20.013 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही',
 '2026-03-11 07:39:21.714 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरला',
 '2026-03-11 07:39:22.106 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के',
 '2026-03-11 07:39:22.316 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तट',
 '2026-03-11 07:39:22.608 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर',
 '2026-03-11 07:39:24.616 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40',
 '2026-03-11 07:39:24.916 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से',
 '2026-03-11 07:39:25.217 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा',
 '2026-03-11 07:39:25.810 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिश',
 '2026-03-11 07:39:26.213 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल',
 '2026-03-11 07:39:26.714 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक',
 '2026-03-11 07:39:27.911 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने',
 '2026-03-11 07:39:28.112 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की',
 '2026-03-11 07:39:28.513 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंज',
 '2026-03-11 07:39:28.615 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी',
 '2026-03-11 07:39:28.715 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी',
 '2026-03-11 07:39:28.816 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई',
 '2026-03-11 07:39:29.117 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई है',
 '2026-03-11 07:39:29.711 | info | backend.services.srt_broadcast_manager | [SRT] Final Speaker=Guest-1 | केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है। तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया। इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई है।',
 '2026-03-11 07:39:30.725 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | इनसे',
 '2026-03-11 07:39:30.926 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | इनसे समु',
 '2026-03-11 07:39:31.027 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | इनसे समुद्र',
 '2026-03-11 07:39:31.228 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | इनसे समुद्र में',
 '2026-03-11 07:39:32.627 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछ',
 '2026-03-11 07:39:32.728 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछल',
 '2026-03-11 07:39:32.928 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों',
 '2026-03-11 07:39:33.430 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की',
 '2026-03-11 07:39:33.530 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या',
 '2026-03-11 07:39:33.931 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़े',
 '2026-03-11 07:39:34.132 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी',
 '2026-03-11 07:39:35.633 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और',
 '2026-03-11 07:39:35.825 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री',
 '2026-03-11 07:39:36.326 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री सं',
 '2026-03-11 07:39:36.527 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसा',
 '2026-03-11 07:39:36.829 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन',
 '2026-03-11 07:39:37.731 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेने',
 '2026-03-11 07:39:38.032 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल',
 '2026-03-11 07:39:38.435 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके',
 '2026-03-11 07:39:38.626 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से',
 '2026-03-11 07:39:38.728 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विक',
 '2026-03-11 07:39:38.928 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित',
 '2026-03-11 07:39:39.230 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित होंगे',
 '2026-03-11 07:39:41.575 | info | backend.services.srt_broadcast_manager | [SRT] Final Speaker=Guest-1 | इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित होंगे।',
 '2026-03-11 07:39:44.432 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | आधुन',
 '2026-03-11 07:39:44.735 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | आधुनिका',
 '2026-03-11 07:39:44.835 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | आधुनिका मल',
 '2026-03-11 07:39:45.037 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | आधुनिका मल्स',
 '2026-03-11 07:39:45.229 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Unknown | आधुनिका मल्स्य बंध',
 '2026-03-11 07:39:45.431 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मल्स्य बंधन',
 '2026-03-11 07:39:46.730 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थाप',
 '2026-03-11 07:39:47.031 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित',
 '2026-03-11 07:39:47.933 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये',
 '2026-03-11 07:39:48.335 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धति',
 '2026-03-11 07:39:48.538 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़',
 '2026-03-11 07:39:48.831 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके',
 '2026-03-11 07:39:49.532 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नम',
 '2026-03-11 07:39:49.632 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ ती',
 '2026-03-11 07:39:49.934 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीर्थ',
 '2026-03-11 07:39:50.035 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश',
 '2026-03-11 07:39:50.238 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मे',
 '2026-03-11 07:39:50.430 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय',
 '2026-03-11 07:39:52.137 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर',
 '2026-03-11 07:39:52.631 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा',
 '2026-03-11 07:39:53.443 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल',
 '2026-03-11 07:39:53.634 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा',
 '2026-03-11 07:39:54.035 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्र',
 '2026-03-11 07:39:54.437 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रम',
 '2026-03-11 07:39:54.638 | info | backend.services.srt_broadcast_manager | [SRT] Interim Speaker=Guest-2 | आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिव',

In [3]:
import pandas as pd

In [4]:
# final_df.to_csv("overall-final-11-march.csv")
final_df = pd.read_csv("overall-final-11-march.csv")

In [5]:
import re
from datetime import datetime

def parse_transcript_segments(log_text):
    lines = [l.strip() for l in log_text.strip().split("\n") if l.strip()]
    
    pattern = re.compile(
        r'^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+)\s*\|.*?\[SRT\]\s*(Interim|Final)\s+Speaker=(\S+)\s*\|\s*(.*)$'
    )
    
    segments = []
    current_interims = []
    segment_start_time = None
    
    for line in lines:
        m = pattern.match(line)
        if not m:
            continue
        
        timestamp_str, result_type, speaker, text = m.groups()
        
        if result_type == "Interim":
            if segment_start_time is None:
                segment_start_time = timestamp_str
            current_interims.append(text)
        
        elif result_type == "Final":
            segment_end_time = timestamp_str
            if segment_start_time is None:
                segment_start_time = timestamp_str
            
            segments.append({
                "segment_start_time": segment_start_time,
                "segment_end_time": segment_end_time,
                "interim_results": current_interims,
                "final_result": text,
                "speaker": speaker,
            })
            current_interims = []
            segment_start_time = None
    
    # handle trailing interims with no final
    if current_interims and segment_start_time:
        segments.append({
            "segment_start_time": segment_start_time,
            "segment_end_time": timestamp_str,
            "interim_results": current_interims,
            "final_result": None,
            "speaker": None,
        })
    
    return segments

segments = parse_transcript_segments(transcripts_log)
print(f"Total segments: {len(segments)}")
print()
for i, seg in enumerate(segments[:5]):
    print(f"--- Segment {i} ---")
    print(f"  Start: {seg['segment_start_time']}")
    print(f"  End:   {seg['segment_end_time']}")
    print(f"  Speaker: {seg['speaker']}")
    print(f"  Interims ({len(seg['interim_results'])}): [{seg['interim_results'][0]!r} ... {seg['interim_results'][-1]!r}]" if seg['interim_results'] else "  Interims: []")
    print(f"  Final: {seg['final_result']!r}")
    print()

Total segments: 263

--- Segment 0 ---
  Start: 2026-03-11 07:39:01.309
  End:   2026-03-11 07:39:29.711
  Speaker: Guest-1
  Interims (60): ['केरल' ... 'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई है']
  Final: 'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है। तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया। इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई है।'

--- Segment 1 ---
  Start: 2026-03-11 07:39:30.725
  End:   2026-03-11 07:39:41.575
  Speaker: Guest-1
  Interims (23): ['इनसे' ... 'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित होंगे']
  Final: 'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित होंगे।'

--- Segment 2 ---
  Start: 2026-03-11 07:39:44.432
  End:   2026-03-11 07:40:06.588
  Speaker: Guest-2
  Interims (30): ['आधुन' ... 'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंखला अनुमति']
  Final: 'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंखला अनुमति।'

--- Segment 3 ---
  Start: 2026-03-11 07:40:08.020
  End:   2026-03-11 07:40:44.301
  Speaker: Guest-1
  Interims (53): ['हम आया' ... 'केरल के लिए']
  Final: 'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए। हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे। यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में आगे ले जाएगी।'

--- Segment 4 ---
  Start: 2026-03-11 07:41:02.674
  End:   2026-03-11 07:41:02.674
  Speaker: Unknown
  Interims: []
  Final: 'केरल के लिए।'

In [6]:
final_log_result = set([x['final_result'] for x in segments])
final_result = set(final_df['source_text'].values.tolist())
final_result - final_log_result

set()

In [7]:
segments

[{'segment_start_time': '2026-03-11 07:39:01.309',
  'segment_end_time': '2026-03-11 07:39:29.711',
  'interim_results': ['केरल',
   'केरल में',
   'केरल में हमारी',
   'केरल में हमारी सरकार',
   'केरल में हमारी सरकार द्वारा',
   'केरल में हमारी सरकार द्वारा आधुन',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्म',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोम',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है',
   'तटी',
   'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है तटीय',
   'तटीय क्षेत्र',
   'तटीय क्षेत्रों',
   'तटीय क्षेत्रों तक',
   'तटीय क्षेत्रों तक योजना',
   'तटीय क्षेत्रों तक योजनाओं',
   'तटीय क्षेत्रों तक योजनाओं का',
   'तटीय क्षेत्रों तक योजनाओं का लाभ',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचा',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सा',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र',
   'और',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरला',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तट',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिश',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंज',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई',
   'तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई है'],
  'final_result': 'केरल में हमारी सरकार द्वारा आधुनिक फीस फार्मिंग सिस्टम को प्रोमोट किया जा रहा है। तटीय क्षेत्रों तक योजनाओं का लाभ पहुंचाने के लिए सागर मित्र और मत्स्य सेवा केंद्र का नेटवर्क भी बनाया गया। इसके साथ ही केरलम के तटों पर 40 से ज्यादा आर्टिफिशियल रेफरिक लगाने की मंजूरी दी गई है।',
  'speaker': 'Guest-1'},
 {'segment_start_time': '2026-03-11 07:39:30.725',
  'segment_end_time': '2026-03-11 07:39:41.575',
  'interim_results': ['इनसे',
   'इनसे समु',
   'इनसे समुद्र',
   'इनसे समुद्र में',
   'इनसे समुद्र में मछ',
   'इनसे समुद्र में मछल',
   'इनसे समुद्र में मछलियों',
   'इनसे समुद्र में मछलियों की',
   'इनसे समुद्र में मछलियों की संख्या',
   'इनसे समुद्र में मछलियों की संख्या बढ़े',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री सं',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसा',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेने',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विक',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित',
   'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित होंगे'],
  'final_result': 'इनसे समुद्र में मछलियों की संख्या बढ़ेगी और समुद्री संसाधन सस्टेनेबल तरीके से विकसित होंगे।',
  'speaker': 'Guest-1'},
 {'segment_start_time': '2026-03-11 07:39:44.432',
  'segment_end_time': '2026-03-11 07:40:06.588',
  'interim_results': ['आधुन',
   'आधुनिका',
   'आधुनिका मल',
   'आधुनिका मल्स',
   'आधुनिका मल्स्य बंध',
   'आधुनिका मल्स्य बंधन',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थाप',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धति',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नम',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ ती',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीर्थ',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मे',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्र',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रम',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिव',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंख',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंखला',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंखला अनु',
   'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंखला अनुमति'],
  'final_result': 'आधुनिका मलसीय बंदरदीगड़म्राल स्थापित ये पद्धतिगढ़ ओके नमूड़ तीरदेश मेघालय सागर मित्रा मल्स्य सेवा केंद्रमेनिवेड श्रृंखला अनुमति।',
  'speaker': 'Guest-2'},
 {'segment_start_time': '2026-03-11 07:40:08.020',
  'segment_end_time': '2026-03-11 07:40:44.301',
  'interim_results': ['हम आया',
   'हम आया म',
   'हम साथ जमाई',
   'हमारा',
   'हमारा संकल्प',
   'हमारा संकल्प है',
   'हमारा संकल्प है कि',
   'हमारा संकल्प है कि के',
   'हमारा संकल्प है कि केरल',
   'हमारा संकल्प है कि केरलम',
   'हमारा संकल्प है कि केरलम के हर',
   'हमारा संकल्प है कि केरलम के हर परिवार',
   'हमारा संकल्प है कि केरलम के हर परिवार के',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में सम',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल की अर्थ',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भाव',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विक',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण के',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण के आधार',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारश',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और',
   'है और यही',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भाव',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विक',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करल',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में आगे',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में आगे ले',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में आगे ले जाएगी',
   'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में आगे ले जाएगी केरल',
   'केरल के लिए'],
  'final_result': 'हमारा संकल्प है कि केरलम के हर परिवार के जीवन में समृद्धि आए। हमारे केरल में अर्थव्यवस्था नई ऊंचाइयों तक पहुंचे। यही भावना विकसित भारतीय निर्माण की भी आधारशिला है और यही भावना हमें विकसित करलम के दिशा में आगे ले जाएगी।',
  'speaker': 'Guest-1'},
 {'segment_start_time': '2026-03-11 07:41:02.674',
  'segment_end_time': '2026-03-11 07:41:02.674',
  'interim_results': [],
  'final_result': 'केरल के लिए।',
  'speaker': 'Unknown'},
 {'segment_start_time': '2026-03-11 07:41:04.453',
  'segment_end_time': '2026-03-11 07:41:07.308',
  'interim_results': ['मैं आप', 'मैं आप देख', 'मैं आप देख रहा हूँ'],
  'final_result': 'मैं आप देख रहा हूँ।',
  'speaker': 'Guest-1'},
 {'segment_start_time': '2026-03-11 07:41:08.656',
  'segment_end_time': '2026-03-11 07:41:26.561',
  'interim_results': ['कितना',
   'कितना अनुशा',
   'कितना अनुशासन',
   'कितना अनुशासन और',
   'कितना अनुशासन और इतनी',
   'कितना अनुशासन और इतनी बड़ी',
   'कितना अनुशासन और इतनी बड़ी ता',
   'कितना अनुशासन और इतनी बड़ी तादाद',
   'कितना अनुशासन और इतनी बड़ी तादाद में',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हा',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी और',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी और मैं',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी और मैं देख',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी और मैं देख रहा हूँ',
   'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी और मैं देख रहा हूँ बाहर'],
  'final_result': 'कितना अनुशासन और इतनी बड़ी तादाद में माताओं बहनों की हाँजी और मैं देख रहा हूँ बाहर।',
  'speaker': 'Guest-1'},
 {'segment_start_time': '2026-03-11 07:41:27.773',
  'segment_end_time': '2026-03-11 07:42:12.588',
  'interim_results': ['सुन',
   'सुन पाते',
   'सुन पाते होंगे',
   'सुन पाते होंगे नहीं',
   'सुन पाते होंगे नहीं पाते',
   'सुन पाते होंगे नहीं पाते किसी',
   'सुन पाते होंगे नहीं पाते किसी कागजा',
   'सुन पाते होंगे नहीं पाते किसी कागजात में',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझ',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इन',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्प',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी',
   'लिए जी रहे हैं',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील करना',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील करना जो',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील करना जोरा',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील करना जोरा सभा के',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील करना जोरा सभा के प्रयास',
   'सुन पाते होंगे नहीं पाते किसी कागजात में आपका आना मैं समझता हूँ आप इनसे किन संकल्पों के लिए जी रहे हैं और अपील करना जोरा सभा के प्रयास आपकी',

In [14]:
from datetime import timedelta

segment_lookup = {seg['final_result']: seg for seg in segments}

ist_offset = timedelta(hours=5, minutes=30)

def lookup_segment(source_text):
    seg = segment_lookup.get(source_text)
    if seg is None:
        return pd.Series({
            'segment_start_time_ist': None,
            'segment_end_time_ist': None,
            'segment_duration_s': None,
            'num_interims': None,
        })
    
    start = datetime.strptime(seg['segment_start_time'], '%Y-%m-%d %H:%M:%S.%f') + ist_offset
    end = datetime.strptime(seg['segment_end_time'], '%Y-%m-%d %H:%M:%S.%f') + ist_offset
    duration = (end - start).total_seconds()
    
    return pd.Series({
        'segment_start_time_ist': start,
        'segment_end_time_ist': end,
        'segment_duration_s': round(duration, 3),
        'num_interims': len(seg['interim_results']),
    })

new_cols = ['segment_start_time_ist', 'segment_end_time_ist', 'segment_duration_s', 'num_interims']
dupe_cols = [c for c in final_df.columns if c in new_cols or any(c.startswith(n + '.') for n in new_cols)]
if dupe_cols:
    final_df = final_df.drop(columns=dupe_cols)

timing_cols = final_df['source_text'].apply(lookup_segment)
final_df[new_cols] = timing_cols
final_df['segment_start_time_ist'] = pd.to_datetime(final_df['segment_start_time_ist'])
final_df['segment_end_time_ist'] = pd.to_datetime(final_df['segment_end_time_ist'])

matched = final_df['segment_start_time_ist'].notna().sum()
print(f"Matched {matched}/{len(final_df)} rows")
final_df[['source_text', 'segment_start_time_ist', 'segment_end_time_ist', 'segment_duration_s', 'num_interims']].head(10)

Matched 120/120 rows

,source_text,segment_start_time_ist,segment_end_time_ist,segment_duration_s,num_interims
0,"नमस्कार, हम एरनाकुलम।",2026-03-11 14:26:00.870,2026-03-11 14:26:03.608,2.738,6
1,जय केरला।,2026-03-11 14:26:15.068,2026-03-11 14:26:16.310,1.242,3
2,10 डेज़ और तगड़े।,2026-03-11 14:26:18.597,2026-03-11 14:26:29.109,10.512,9
3,केरला को।,2026-03-11 14:26:34.798,2026-03-11 14:26:36.514,1.716,3
4,"केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...",2026-03-11 14:26:38.067,2026-03-11 14:26:44.713,6.646,12
5,मुझे बहुत गर्व है अब पूरा देश और दुनिया इस महा...,2026-03-11 14:26:45.798,2026-03-11 14:26:56.023,10.225,13
6,केरलम कहकर पुकार रहा है।,2026-03-11 14:26:57.108,2026-03-11 14:27:00.302,3.194,8
7,और मुझे इस बात का भी गर्व है।,2026-03-11 14:27:02.070,2026-03-11 14:27:05.324,3.254,5
8,ऐतिहासिक काम भी।,2026-03-11 14:27:06.667,2026-03-11 14:27:09.202,2.535,4
9,बी जे पीएन डीए सरकार ने किया है।,2026-03-11 14:27:10.771,2026-03-11 14:27:13.919,3.148,7

In [15]:
final_df

,Unnamed: 0,_id,doc_type,session_id,timestamp,source_text,source_text_length,translated_texts,audio_base64,audio_base64s,...,is_english_by_vocab,asr_decision,relative_time_s,audio_duration_s,malayalam_translated_text,audio_base64_malayalam,segment_start_time_ist,segment_end_time_ist,segment_duration_s,num_interims
0,26,{'$oid': '69b12e246b023d0cb6dd3731'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:03.969Z'},"नमस्कार, हम एरनाकुलम।",21,"{'malayalam': 'നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നി...",UklGRsSFBABXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsSFBABXQVZFZm10IBAAAAABAAE...,...,False,reject,0.000,2.323125,"നമസ്കാരം, ഞങ്ങൾ എറണാകുളത്തിൽ നിന്നാണ്.",UklGRlaRAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 14:26:00.870,2026-03-11 14:26:03.608,2.738,6
1,27,{'$oid': '69b12e316b023d0cb6dd3732'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:16.565Z'},जय केरला।,9,{'malayalam': 'ജയ് കേരളം.'},UklGRhR6AgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRhR6AgBXQVZFZm10IBAAAAABAAE...,...,False,reject,12.275,1.395625,ജയ് കേരളം.,UklGRl5XAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 14:26:15.068,2026-03-11 14:26:16.310,1.242,3
2,28,{'$oid': '69b12e3e6b023d0cb6dd3733'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:29.440Z'},10 डेज़ और तगड़े।,17,"{'malayalam': '10 ദിവസത്തേക്ക് ഇത് മതിയാകും, ക...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,...,False,reject,25.335,3.647500,"10 ദിവസത്തേക്ക് ഇത് മതിയാകും, കൂടുതൽ ആവശ്യമില്ല.",UklGRhzkAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 14:26:18.597,2026-03-11 14:26:29.109,10.512,9
3,29,{'$oid': '69b12e456b023d0cb6dd3734'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:36.708Z'},केरला को।,9,{'malayalam': 'കേരളത്തിലേക്ക്.'},UklGRlQvAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRlQvAQBXQVZFZm10IBAAAAABAAE...,...,False,reject,32.214,1.046750,കേരളത്തിലേക്ക്.,UklGRpBBAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 14:26:34.798,2026-03-11 14:26:36.514,1.716,3
4,30,{'$oid': '69b12e4d6b023d0cb6dd3735'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T08:56:45.073Z'},"केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...",50,"{'malayalam': 'കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്,...",UklGRrSNAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRrSNAwBXQVZFZm10IBAAAAABAAE...,...,False,reject,40.966,3.936125,"കേരളം എന്ന് വിളിക്കപ്പെടുന്നത്, നിങ്ങളുടെ മനസ്...",UklGRib2AABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 14:26:38.067,2026-03-11 14:26:44.713,6.646,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,182,{'$oid': '69b136786b023d0cb6dd37cd'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.563Z'},ये दिखा रहा है।,15,{'malayalam': 'അത് കാണിക്കുകയാണ്.'},UklGRsQTAQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRsQTAQBXQVZFZm10IBAAAAABAAE...,...,False,reject,2132.051,2.048750,അത് കാണിക്കുകയാണ്.,UklGRjCAAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 15:01:36.127,2026-03-11 15:01:36.320,0.193,3
116,183,{'$oid': '69b1367b6b023d0cb6dd37ce'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:38.339Z'},यहाँ आने वाले चुनावों में हवा का रुख क्या होगा...,91,{'malayalam': 'വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളി...,UklGRkRiBQBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkRiBQBXQVZFZm10IBAAAAABAAE...,...,False,reject,2134.579,6.706875,വരാനിരിക്കുന്ന തിരഞ്ഞെടുപ്പുകളിൽ രാഷ്ട്രീയ കാല...,UklGRlKjAQBXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 15:01:36.639,2026-03-11 15:01:37.787,1.148,11
117,184,{'$oid': '69b1367b6b023d0cb6dd37cf'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:31:36.910Z'},केरल में बनने वाली बीजेपी एनडीए सरकार यहाँ के ...,155,{'malayalam': 'കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള...,UklGRtTTDwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRtTTDwBXQVZFZm10IBAAAAABAAE...,...,False,reject,2135.029,14.898625,കേരളത്തിൽ ബിജെപി നേതൃത്വത്തിലുള്ള എൻഡിഎ സർക്കാ...,UklGRk6jAwBXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 15:01:32.412,2026-03-11 15:01:35.817,3.405,20
118,186,{'$oid': '69b136a26b023d0cb6dd37d1'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:17.570Z'},मेरे साथ बोलिए भारत माता की।,28,"{'malayalam': 'എന്നൊപ്പം ചേർന്ന് ""ഭാരത് മാതാ ...",UklGRkSpAwBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRkSpAwBXQVZFZm10IBAAAAABAAE...,...,False,reject,2173.478,3.560125,"എന്നൊപ്പം ചേർന്ന് ""ഭാരത് മാതാ കി ജയ്"" എന്ന് വ...",UklGRqbeAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 15:02:14.316,2026-03-11 15:02:17.145,2.829,5
119,187,{'$oid': '69b136ac6b023d0cb6dd37d2'},final_result,04ce446d-5396-45c9-91e5-57906365fa10,{'$date': '2026-03-11T09:32:27.622Z'},भारत माता के भारत माता के वंदे वंदे।,36,"{'malayalam': 'ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന...",UklGRjSxAgBXQVZFZm10IBAAAAABAAEAIlYAAESsAAACAB...,{'malayalam': 'UklGRjSxAgBXQVZFZm10IBAAAAABAAE...,...,False,reject,2183.377,3.827375,"ഭാരത മാതാവിന് ജയ്, ഭാരത മാതാവിന് ജയ്.",UklGRlrvAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACAB...,2026-03-11 15:02:18.896,2026-03-11 15:02:27.243,8.347,10

In [17]:
final_df['source_text']

0                                  नमस्कार, हम एरनाकुलम।
1                                              जय केरला।
2                                      10 डेज़ और तगड़े।
3                                              केरला को।
4      केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...
                             ...
115                                      ये दिखा रहा है।
116    यहाँ आने वाले चुनावों में हवा का रुख क्या होगा...
117    केरल में बनने वाली बीजेपी एनडीए सरकार यहाँ के ...
118                         मेरे साथ बोलिए भारत माता की।
119                 भारत माता के भारत माता के वंदे वंदे।
Name: source_text, Length: 120, dtype: str

In [18]:
import aiohttp
import asyncio

BASE_URL = "http://172.16.9.11:10021"
TRANSLATION_PATH = "/voice_stream/translation"

async def translate_hi_to_en(text, session):
    payload = {
        "translation_id": "trans_001",
        "secret_key": "gnani_translate_2026",
        "source_lang": "hi-IN",
        "target_lang": "en-IN",
        "text": text,
    }
    async with session.post(
        f"{BASE_URL}{TRANSLATION_PATH}",
        json=payload,
        headers={"Content-Type": "application/json"},
    ) as response:
        response.raise_for_status()
        return await response.json()

async def translate_all(texts):
    async with aiohttp.ClientSession() as session:
        results = []
        for i, text in enumerate(texts):
            try:
                result = await translate_hi_to_en(text, session)
                translated = result if isinstance(result, str) else result.get("translated_text", result.get("text", str(result)))
                results.append(translated)
            except Exception as e:
                print(f"[{i}] Error: {e}")
                results.append(None)
            if (i + 1) % 20 == 0:
                print(f"Translated {i + 1}/{len(texts)}")
        return results

texts = final_df['source_text'].tolist()
english_texts = await translate_all(texts)
final_df['english_text'] = english_texts

print(f"Done. Translated {sum(1 for t in english_texts if t is not None)}/{len(texts)}")
final_df[['source_text', 'english_text']].head(10)

Translated 20/120
Translated 40/120
Translated 60/120
Translated 80/120
Translated 100/120
Translated 120/120
Done. Translated 120/120

,source_text,english_text
0,"नमस्कार, हम एरनाकुलम।","Hello, we are from Ernakulam."
1,जय केरला।,Hail Kerala.
2,10 डेज़ और तगड़े।,10 days and it’s done.
3,केरला को।,To Kerala.
4,"केरलम के रूप में जाना जाए, ये आपके दिल की आवाज...","Kerala, as you know it, was what your heart to..."
5,मुझे बहुत गर्व है अब पूरा देश और दुनिया इस महा...,I am very proud that the entire country and th...
6,केरलम कहकर पुकार रहा है।,Kerala is calling out.
7,और मुझे इस बात का भी गर्व है।,And I am also proud of that.
8,ऐतिहासिक काम भी।,It’s also a historic achievement.
9,बी जे पीएन डीए सरकार ने किया है।,The BJP-NDA government has done it.

In [20]:
final_df['segment_asr_log_time'] = final_df['segment_end_time_ist']

In [27]:
final_df['segment_translated_time'] = final_df['segment_end_time_ist'] + pd.to_timedelta(final_df['llm_latency_seconds'], unit='s')
final_df['segment_tts_start_stream_time'] = final_df['segment_translated_time'] + pd.to_timedelta(final_df['tts_generation_delay_seconds'], unit='s')

In [23]:
final_df['llm_latency_seconds']

0      0.360
1      0.255
2      0.330
3      0.193
4      0.360
       ...
115    0.242
116    0.551
117    1.092
118    0.425
119    0.379
Name: llm_latency_seconds, Length: 120, dtype: float64

In [22]:
final_df['tts_generation_delay_seconds']

0      0.830
1      0.510
2      0.694
3      0.306
4      0.692
       ...
115    0.288
116    1.040
117    2.916
118    0.707
119    0.554
Name: tts_generation_delay_seconds, Length: 120, dtype: float64

In [32]:
final_df['malayalam_text'] = final_df['malayalam_translated_text']

In [34]:
final_df[['segment_start_time_ist', 'segment_duration_s', 'segment_asr_log_time', 'segment_translated_time', 'segment_tts_start_stream_time','source_text','english_text', 'malayalam_text']].to_csv('pm_modi_speech_11_mar_erunakulam.csv', index=False)